{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyM0l2Exb77oDjRAGlWL08vl"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"id":"DerR-Zup6BBA"},"outputs":[],"source":["### Exception Handing ###\n","\n","numberOne = 5\n","numberTwo = 1\n","numberTwo = \"1\"\n","\n","# Exceocion base: try except\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print(\"No se ha producido un error\")\n","except:\n","  # Se ejecuta si se produce una excepcion\n","   print(\"Se ha producido un error\")\n","\n","# Flujo completo de una excepcion: try except else finally\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print(\"No se ha producido un error\")\n","except:\n","   print(\"Se ha producido un error\")\n","else: # Opcional\n","   # Se ejecita si no se produce una excepcion\n","   print(\"L ejecucion continua correctamente\")\n","finally: #Opcional\n","  # Se ejecuta siempre\n","  print(\"La ejecucion continua\")\n","\n","# Excepciones por tipo\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print(\"No se ha producido un error\")\n","except ValueError:\n","   print(\"Se ha producido un ValueError\")\n","except TypeError:\n","   print(\"Se ha producido un TypeError\")\n","\n","# Captura de la informacion de la excepcion\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print(\"No se ha producido un error\")\n","except ValueError as error:\n","   print(error)\n","except Exception as my_random_error_name:\n","   print()\n"]}]}